name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

# --- LA LIGNE MAGIQUE POUR AUTORISER LE DÉPLOIEMENT ---
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive 
          fetch-depth: 0        

      - name: Setup uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          enable-cache: false
        
      - name: Conversion BibTeX vers JSON
        run: uv run scripts/bib_to_json.py

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.162.1'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
