name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

# --- LA LIGNE MAGIQUE POUR AUTORISER LE DÉPLOIEMENT ---
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive 
          fetch-depth: 0        

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false # --- DÉSACTIVE LE WARNING UV ---
        
      - name: Conversion BibTeX vers JSON
        run: uv run scripts/bib_to_json.py

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.123.7'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public