name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Un seul Checkout au tout début, avec toutes les options
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # Fetch Hugo themes
          fetch-depth: 0        # Fetch all history for .GitInfo and .Lastmod

      # 2. --- AJOUT POUR LA BIBLIOGRAPHIE ---
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        
      - name: Conversion BibTeX vers JSON
        run: uv run scripts/bib_to_json.py
      # -----------------------------------

      # 3. Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.123.7'
          extended: true

      # 4. Compilation du site
      - name: Build
        run: hugo --minify

      # 5. Déploiement
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public